**Numpy exercises**

Collection of Numpy exercises helpful for new and experience users both.


Note : Regularly I will add new exercises  

In [1]:
#import numpy library

import numpy as np

#print numpy version

print(np.__version__)

1.14.2


In [3]:
# null vector of size 5

a = np.zeros(5)

print(a)

#change value of 2nd to 1
a[3] = 1

print('New elements of a after change'
     )
print(a)

[0. 0. 0. 0. 0.]
New elements of a after change
[0. 0. 0. 1. 0.]


In [4]:
#Create a vector with values ranging from 5 to 19

a = np.arange(5,20)

print(a)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [7]:
#How to generate five random numbers

a = np.random.normal(size=5)

print(a)

# generate 4 random integers between 10 and 20.

a_4 = np.random.randint(low=10, high=20, size=4)

print('4 random numbers between 10 and 20')

print(a_4)

[-2.02250375  0.04751625 -1.58640887  1.05509188  0.16042023]
4 random numbers between 10 and 20
[17 14 12 18]


In [16]:
# How to find min, max values

a = np.array([5, 0, 3, 3, 7, 9])

print(a)

# min value

a_min = min(a)
print('Minimum :  ',a_min)

# max value

a_max = max(a)
print('Maximum :  ',a_max)


[5 0 3 3 7 9]
Minimum :   0
Maximum :   9




**Numpy Array Indexing**

In [18]:
a = np.array([5, 0, 3, 3, 7, 9])

print(a)

print('First element: ',a[0])      # indexing starts from 0

print('third element: ',a[2])

[5 0 3 3 7 9]
First element:  5
third element:  3


In [19]:
# To index from the end of the array, you can use negative indices:

print( a[-1] )

9


In [22]:
#In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

a2 = np.array([[3, 5, 2, 4],[7, 6, 8, 8],[1, 6, 7, 7]])

print(a2)

# get first item

print('at 0,0 Position')

print(a2[0,0])

print('at 0,2 Position')

print(a2[0,2])

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
at 0,0 Position
3
at 0,2 Position
2


Array Values can be modified using index notation:

In [23]:
a = np.array([5, 0, 3, 3, 7, 9])

print(a)

# change value of first index 

a[0] = 22

print('New array')

print(a)

[5 0 3 3 7 9]
New array
[22  0  3  3  7  9]


**Array Slicing**

Syntex : [start:stop:step]

In [25]:
a = np.arange(10)

print(a)

# first four elements

print( a[:4] )

# elements after index 4

print( a[4:] )


# every other element, starting at index 1

print( a[1::2]  )

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3]
[4 5 6 7 8 9]
[1 3 5 7 9]
