**Numpy Basics**

NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. Using NumPy, mathematical and logical operations on arrays can be performed.


NumPy’s array class is called ndarray. It is also known by the alias array. Note that numpy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality. 
The more important attributes of an ndarray object are:


**ndarray.ndim**
the number of axes (dimensions) of the array. In the Python world, the number of dimensions is referred to as rank.

**ndarray.shape**
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the rank, or number of dimensions, ndim.

**ndarray.size**
the total number of elements of the array. This is equal to the product of the elements of shape.

**Examole:**



```
# This is formatted as code
```




In [0]:
import numpy as np

a = np.arange(15).reshape(3, 5)

print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [0]:
a.ndim

2

In [0]:
a.size

15

In [0]:
type(a)

numpy.ndarray

**Numpy Array Creation**

There are several ways to create arrays.

For example, you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.




In [2]:
import numpy as np

a = np.array([2,3,4,5,6])

a

array([2, 3, 4, 5, 6])

float type array

In [4]:
b = np.array([1.3,2.2,4.5])

b.dtype

dtype('float64')

Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.


The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

In [5]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones( (2,3,4), dtype=np.int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)






To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists

**Syntex**

arange([start,] stop[, step,][, dtype]) : Returns an array with evenly spaced elements as per the interval. The interval mentioned is half opened i.e. [Start, Stop)


Example:

In [7]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

### 1d array


In [8]:
a = np.arange(4)

print(a)

[0 1 2 3]


 ### 2d array

In [12]:
n2d = np.arange(12).reshape(4,3)

print(n2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


### Basic Operations

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [15]:
a = np.array([1,2,3,4])

b = np.arange(4)

print(b)

# add
c = a+b

print(c)

[0 1 2 3]
[1 3 5 7]


In [17]:
# multiply 

print(a*3)

[ 3  6  9 12]


**Indexing, Slicing and Iterating**

One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

Contents of ndarray object can be accessed and modified by indexing or slicing, just like Python's in-built container objects.
items in ndarray object follows zero-based index.

In [2]:
import numpy as np

a = np.arange(10)**3
print(a)

[  0   1   8  27  64 125 216 343 512 729]


In [5]:
print(a[4])    # fourth element

64


In [6]:
print(a[3:6])

[ 27  64 125]


Basic slicing is an extension of Python's basic concept of slicing to n dimensions. A Python slice object is constructed by giving start, stop, and step parameters to the built-in slice function. This slice object is passed to the array to extract a part of array.

**Example:**

When this slice object is passed to the ndarray, a part of it starting with index 2 up to 7 with a step of 2 is sliced.

In [7]:
a = np.arange(10) 

b = a[2:7:2] 
print(b)

[2 4 6]


In [9]:
# slice items starting from index
print (a[2:])

[2 3 4 5 6 7 8 9]


In [12]:
#The above description applies to multi-dimensional ndarray too.

a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a)

print('Now we will slice the array from the index a[1:]')
print (a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]




**Iterating Over Array**

NumPy package contains an iterator object numpy.nditer. It is an efficient multidimensional iterator object using which it is possible to iterate over an array. Each element of an array is visited using Python’s standard Iterator interface.

In [16]:
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)


print ('Original array is:')
print (a)
print ('\n')

print ('Modified array is:')
for x in np.nditer(a):
   print (x)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


**Modifying Array Values**

By default, the nditer treats the input array as a read-only object. To modify the array elements, you must specify either read-write or write-only mode. This is controlled with per-operand flags.

**Example**

In [17]:
a = np.arange(6).reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


In [18]:
for x in np.nditer(a, op_flags=['readwrite']):
  x[...] = 2 * x
  
  print(a)

[[0 1 2]
 [3 4 5]]
[[0 2 2]
 [3 4 5]]
[[0 2 4]
 [3 4 5]]
[[0 2 4]
 [6 4 5]]
[[0 2 4]
 [6 8 5]]
[[ 0  2  4]
 [ 6  8 10]]
